api_version: 1
auto_merge:
  - dependency: gds-api-adapters
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: gds-sso
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govspeak
    allowed_semver_bumps:
      - patch
      - minor
 - dependency: govuk_ab_testing
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_app_config
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_frontend_toolkit
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_publishing_components
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_schemas
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_sidekiq
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_test
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: plek
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: rubocop-govuk
    allowed_semver_bumps:
      - patch
      - minor
