# This file has a list of organisation content_id's
#Â that are allowed tag their documents to the topic taxonomy

- "71381a6e-aa5c-43ae-a982-be9bfd46ea5b" # Education & Skills Funding Agency
- "b9fc8528-81d1-419b-8748-6c00be71044b" # Education Funding Agency (replaced by Education & Skills Funding Agency in April 2017)
- "ebd15ade-73b2-4eaf-b1c3-43034a42eb37" # Department for Education
- "60de9b00-a982-4449-a995-f2353e86fb95" # Higher Education Statistics Agency
- "a081cd5b-c41d-4389-ac65-982e7570680d" # Institute for Apprenticeships
- "e1cbab66-b0d3-4186-917c-afd4f3fb6967" # National College for Teaching and Leadership
- "e7f33769-a539-4fb4-b24f-f6c1cabc3f59" # Office of the Schools Adjudicator
- "83f6e93f-bb2c-46ab-9b02-394f972b7030" # Ofqual
- "ad5f6169-ac7b-4382-9eb6-e58af71a2f00" # Ofsted
- "3e5a6924-b369-4eb3-8b06-3c0814701de4" # Skills Funding Agency (replaced by Education & Skills Funding Agency in April 2017)
- "863ffacd-d313-49c1-b856-58fe0799fd41" # Standards and Testing Agency
- "9a9111aa-1db8-4025-8dd2-e08ec3175e72" # Student Loans Company
- "30637a3a-bd24-4db6-b172-c49500bf50a5" # Schools Commissioners Group
- "db994552-7644-404d-a770-a2fe659c661f" # Department for International Development
- "9adfc4ed-9f6c-4976-a6d8-18d34356367c" # Foreign & Commonwealth Office
- "04148522-b0c1-4137-b687-5f3c3bdd561a" # UK Visas and Immigration
- "082092f1-656c-470e-b024-229dc6e750e9" # Department for International Trade
- "f323e83c-868b-4bcb-b6e2-a8f9bb40397e" # Department for Exiting the European Union
