name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Rails
    uses: alphagov/govuk-infrastructure/.github/workflows/test-rails.yaml@main
    with:
      requiresJavaScript: true
      requiresRedis: true
      requiresMySQL: true
      mysqlUsername: whitehall
      mysqlPassword: whitehall
      extraSystemDependencies: 'ghostscript'
