name: Deploy

run-name: Deploy ${{ inputs.gitRef || github.event.release.tag_name  }} to ${{ inputs.environment || 'integration' }}

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
        - integration
        - staging
        - production
        default: 'integration'
  release:
    types: [released]

jobs:
  build-and-publish-image:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'v')
    name: Build and publish image
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-multiarch-image.yml@main
    with:
      gitRef: ${{ inputs.gitRef || github.event.release.tag_name }}
    permissions:
      id-token: write
      contents: read
      packages: write
  trigger-deploy:
    name: Trigger deploy to ${{ inputs.environment || 'integration' }}
    needs: build-and-publish-image
    uses: alphagov/govuk-infrastructure/.github/workflows/deploy.yml@main
    with:
      imageTag: ${{ needs.build-and-publish-image.outputs.imageTag }}
      environment: ${{ inputs.environment || 'integration' }}
    secrets:
      WEBHOOK_TOKEN: ${{ secrets.GOVUK_ARGO_EVENTS_WEBHOOK_TOKEN }}
      WEBHOOK_URL: ${{ secrets.GOVUK_ARGO_EVENTS_WEBHOOK_URL }}
      GH_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
