name: Run lint:scss

on: workflow_call

jobs:
  run-lint-scss:
    name: Run Stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Run lint:scss
        run: yarn run lint:scss
